// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/strrl/kubernetes-auditing-dashboard/ent"
)

type AuditEventPagination struct {
	Total           int               `json:"total"`
	Page            int               `json:"page"`
	PageSize        int               `json:"pageSize"`
	TotalPages      int               `json:"totalPages"`
	HasNextPage     bool              `json:"hasNextPage"`
	HasPreviousPage bool              `json:"hasPreviousPage"`
	Rows            []*ent.AuditEvent `json:"rows"`
}
