// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"

	"github.com/strrl/kubernetes-auditing-dashboard/ent"
)

type AuditEventPagination struct {
	Total           int               `json:"total"`
	Page            int               `json:"page"`
	PageSize        int               `json:"pageSize"`
	TotalPages      int               `json:"totalPages"`
	HasNextPage     bool              `json:"hasNextPage"`
	HasPreviousPage bool              `json:"hasPreviousPage"`
	Rows            []*ent.AuditEvent `json:"rows"`
}

// Represents a single field change in a diff
type DiffEntry struct {
	// JSON path to the changed field (e.g., "spec.replicas")
	Path string `json:"path"`
	// Previous value before the change
	OldValue string `json:"oldValue"`
	// New value after the change
	NewValue string `json:"newValue"`
}

// Represents a single lifecycle event for a Kubernetes resource
type LifecycleEvent struct {
	// Unique identifier for the audit event
	ID int `json:"id"`
	// Type of lifecycle event
	Type string `json:"type"`
	// ISO 8601 timestamp when the event occurred
	Timestamp time.Time `json:"timestamp"`
	// User or service account that triggered the event
	User string `json:"user"`
	// Complete resource state at the time of this event (YAML as JSON)
	ResourceState string `json:"resourceState"`
	// Previous resource state before this event (YAML as JSON). Only populated for UPDATE events.
	PreviousState *string `json:"previousState,omitempty"`
	// Diff showing changes from previous version (null for CREATE and DELETE events)
	Diff *ResourceDiff `json:"diff,omitempty"`
}

// Represents the diff between two consecutive resource versions
type ResourceDiff struct {
	// Fields that were added in this update
	Added *string `json:"added,omitempty"`
	// Fields that were removed in this update
	Removed *string `json:"removed,omitempty"`
	// Fields that were modified, with old and new values
	Modified []*DiffEntry `json:"modified"`
}
