package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
)

// ImportResourceKindTsv is the resolver for the importResourceKindTSV field.
func (r *mutationResolver) ImportResourceKindTsv(ctx context.Context, tsv string) (int, error) {
	return 0, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
