// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/auditevent"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/predicate"
)

// AuditEventQuery is the builder for querying AuditEvent entities.
type AuditEventQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.AuditEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuditEventQuery builder.
func (aeq *AuditEventQuery) Where(ps ...predicate.AuditEvent) *AuditEventQuery {
	aeq.predicates = append(aeq.predicates, ps...)
	return aeq
}

// Limit the number of records to be returned by this query.
func (aeq *AuditEventQuery) Limit(limit int) *AuditEventQuery {
	aeq.ctx.Limit = &limit
	return aeq
}

// Offset to start from.
func (aeq *AuditEventQuery) Offset(offset int) *AuditEventQuery {
	aeq.ctx.Offset = &offset
	return aeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aeq *AuditEventQuery) Unique(unique bool) *AuditEventQuery {
	aeq.ctx.Unique = &unique
	return aeq
}

// Order specifies how the records should be ordered.
func (aeq *AuditEventQuery) Order(o ...OrderFunc) *AuditEventQuery {
	aeq.order = append(aeq.order, o...)
	return aeq
}

// First returns the first AuditEvent entity from the query.
// Returns a *NotFoundError when no AuditEvent was found.
func (aeq *AuditEventQuery) First(ctx context.Context) (*AuditEvent, error) {
	nodes, err := aeq.Limit(1).All(setContextOp(ctx, aeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{auditevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aeq *AuditEventQuery) FirstX(ctx context.Context) *AuditEvent {
	node, err := aeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuditEvent ID from the query.
// Returns a *NotFoundError when no AuditEvent ID was found.
func (aeq *AuditEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(1).IDs(setContextOp(ctx, aeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{auditevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aeq *AuditEventQuery) FirstIDX(ctx context.Context) int {
	id, err := aeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuditEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuditEvent entity is found.
// Returns a *NotFoundError when no AuditEvent entities are found.
func (aeq *AuditEventQuery) Only(ctx context.Context) (*AuditEvent, error) {
	nodes, err := aeq.Limit(2).All(setContextOp(ctx, aeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{auditevent.Label}
	default:
		return nil, &NotSingularError{auditevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aeq *AuditEventQuery) OnlyX(ctx context.Context) *AuditEvent {
	node, err := aeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuditEvent ID in the query.
// Returns a *NotSingularError when more than one AuditEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (aeq *AuditEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(2).IDs(setContextOp(ctx, aeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{auditevent.Label}
	default:
		err = &NotSingularError{auditevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aeq *AuditEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := aeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuditEvents.
func (aeq *AuditEventQuery) All(ctx context.Context) ([]*AuditEvent, error) {
	ctx = setContextOp(ctx, aeq.ctx, "All")
	if err := aeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuditEvent, *AuditEventQuery]()
	return withInterceptors[[]*AuditEvent](ctx, aeq, qr, aeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aeq *AuditEventQuery) AllX(ctx context.Context) []*AuditEvent {
	nodes, err := aeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuditEvent IDs.
func (aeq *AuditEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aeq.ctx.Unique == nil && aeq.path != nil {
		aeq.Unique(true)
	}
	ctx = setContextOp(ctx, aeq.ctx, "IDs")
	if err = aeq.Select(auditevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aeq *AuditEventQuery) IDsX(ctx context.Context) []int {
	ids, err := aeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aeq *AuditEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Count")
	if err := aeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aeq, querierCount[*AuditEventQuery](), aeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aeq *AuditEventQuery) CountX(ctx context.Context) int {
	count, err := aeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aeq *AuditEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Exist")
	switch _, err := aeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aeq *AuditEventQuery) ExistX(ctx context.Context) bool {
	exist, err := aeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuditEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aeq *AuditEventQuery) Clone() *AuditEventQuery {
	if aeq == nil {
		return nil
	}
	return &AuditEventQuery{
		config:     aeq.config,
		ctx:        aeq.ctx.Clone(),
		order:      append([]OrderFunc{}, aeq.order...),
		inters:     append([]Interceptor{}, aeq.inters...),
		predicates: append([]predicate.AuditEvent{}, aeq.predicates...),
		// clone intermediate query.
		sql:  aeq.sql.Clone(),
		path: aeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Raw string `json:"raw,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuditEvent.Query().
//		GroupBy(auditevent.FieldRaw).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aeq *AuditEventQuery) GroupBy(field string, fields ...string) *AuditEventGroupBy {
	aeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuditEventGroupBy{build: aeq}
	grbuild.flds = &aeq.ctx.Fields
	grbuild.label = auditevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Raw string `json:"raw,omitempty"`
//	}
//
//	client.AuditEvent.Query().
//		Select(auditevent.FieldRaw).
//		Scan(ctx, &v)
func (aeq *AuditEventQuery) Select(fields ...string) *AuditEventSelect {
	aeq.ctx.Fields = append(aeq.ctx.Fields, fields...)
	sbuild := &AuditEventSelect{AuditEventQuery: aeq}
	sbuild.label = auditevent.Label
	sbuild.flds, sbuild.scan = &aeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuditEventSelect configured with the given aggregations.
func (aeq *AuditEventQuery) Aggregate(fns ...AggregateFunc) *AuditEventSelect {
	return aeq.Select().Aggregate(fns...)
}

func (aeq *AuditEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aeq); err != nil {
				return err
			}
		}
	}
	for _, f := range aeq.ctx.Fields {
		if !auditevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aeq.path != nil {
		prev, err := aeq.path(ctx)
		if err != nil {
			return err
		}
		aeq.sql = prev
	}
	return nil
}

func (aeq *AuditEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuditEvent, error) {
	var (
		nodes = []*AuditEvent{}
		_spec = aeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuditEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuditEvent{config: aeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aeq *AuditEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aeq.querySpec()
	_spec.Node.Columns = aeq.ctx.Fields
	if len(aeq.ctx.Fields) > 0 {
		_spec.Unique = aeq.ctx.Unique != nil && *aeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aeq.driver, _spec)
}

func (aeq *AuditEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	_spec.From = aeq.sql
	if unique := aeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aeq.path != nil {
		_spec.Unique = true
	}
	if fields := aeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditevent.FieldID)
		for i := range fields {
			if fields[i] != auditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aeq *AuditEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aeq.driver.Dialect())
	t1 := builder.Table(auditevent.Table)
	columns := aeq.ctx.Fields
	if len(columns) == 0 {
		columns = auditevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aeq.sql != nil {
		selector = aeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aeq.ctx.Unique != nil && *aeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aeq.predicates {
		p(selector)
	}
	for _, p := range aeq.order {
		p(selector)
	}
	if offset := aeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuditEventGroupBy is the group-by builder for AuditEvent entities.
type AuditEventGroupBy struct {
	selector
	build *AuditEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aegb *AuditEventGroupBy) Aggregate(fns ...AggregateFunc) *AuditEventGroupBy {
	aegb.fns = append(aegb.fns, fns...)
	return aegb
}

// Scan applies the selector query and scans the result into the given value.
func (aegb *AuditEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aegb.build.ctx, "GroupBy")
	if err := aegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuditEventQuery, *AuditEventGroupBy](ctx, aegb.build, aegb, aegb.build.inters, v)
}

func (aegb *AuditEventGroupBy) sqlScan(ctx context.Context, root *AuditEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aegb.fns))
	for _, fn := range aegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aegb.flds)+len(aegb.fns))
		for _, f := range *aegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuditEventSelect is the builder for selecting fields of AuditEvent entities.
type AuditEventSelect struct {
	*AuditEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aes *AuditEventSelect) Aggregate(fns ...AggregateFunc) *AuditEventSelect {
	aes.fns = append(aes.fns, fns...)
	return aes
}

// Scan applies the selector query and scans the result into the given value.
func (aes *AuditEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aes.ctx, "Select")
	if err := aes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuditEventQuery, *AuditEventSelect](ctx, aes.AuditEventQuery, aes, aes.inters, v)
}

func (aes *AuditEventSelect) sqlScan(ctx context.Context, root *AuditEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aes.fns))
	for _, fn := range aes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
