// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/auditevent"
)

// AuditEvent is the model entity for the AuditEvent schema.
type AuditEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Raw holds the value of the "raw" field.
	Raw string `json:"raw,omitempty"`
	// Level holds the value of the "level" field.
	Level string `json:"level,omitempty"`
	// AuditID holds the value of the "auditID" field.
	AuditID string `json:"auditID,omitempty"`
	// Verb holds the value of the "verb" field.
	Verb string `json:"verb,omitempty"`
	// UserAgent holds the value of the "userAgent" field.
	UserAgent string `json:"userAgent,omitempty"`
	// RequestTimestamp holds the value of the "requestTimestamp" field.
	RequestTimestamp time.Time `json:"requestTimestamp,omitempty"`
	// StageTimestamp holds the value of the "stageTimestamp" field.
	StageTimestamp time.Time `json:"stageTimestamp,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ApiVersion holds the value of the "apiVersion" field.
	ApiVersion string `json:"apiVersion,omitempty"`
	// ApiGroup holds the value of the "apiGroup" field.
	ApiGroup string `json:"apiGroup,omitempty"`
	// Resource holds the value of the "resource" field.
	Resource string `json:"resource,omitempty"`
	// SubResource holds the value of the "subResource" field.
	SubResource string `json:"subResource,omitempty"`
	// Stage holds the value of the "stage" field.
	Stage        string `json:"stage,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			values[i] = new(sql.NullInt64)
		case auditevent.FieldRaw, auditevent.FieldLevel, auditevent.FieldAuditID, auditevent.FieldVerb, auditevent.FieldUserAgent, auditevent.FieldNamespace, auditevent.FieldName, auditevent.FieldApiVersion, auditevent.FieldApiGroup, auditevent.FieldResource, auditevent.FieldSubResource, auditevent.FieldStage:
			values[i] = new(sql.NullString)
		case auditevent.FieldRequestTimestamp, auditevent.FieldStageTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditEvent fields.
func (_m *AuditEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case auditevent.FieldRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value.Valid {
				_m.Raw = value.String
			}
		case auditevent.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = value.String
			}
		case auditevent.FieldAuditID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auditID", values[i])
			} else if value.Valid {
				_m.AuditID = value.String
			}
		case auditevent.FieldVerb:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verb", values[i])
			} else if value.Valid {
				_m.Verb = value.String
			}
		case auditevent.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userAgent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case auditevent.FieldRequestTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requestTimestamp", values[i])
			} else if value.Valid {
				_m.RequestTimestamp = value.Time
			}
		case auditevent.FieldStageTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stageTimestamp", values[i])
			} else if value.Valid {
				_m.StageTimestamp = value.Time
			}
		case auditevent.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case auditevent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case auditevent.FieldApiVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apiVersion", values[i])
			} else if value.Valid {
				_m.ApiVersion = value.String
			}
		case auditevent.FieldApiGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apiGroup", values[i])
			} else if value.Valid {
				_m.ApiGroup = value.String
			}
		case auditevent.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				_m.Resource = value.String
			}
		case auditevent.FieldSubResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subResource", values[i])
			} else if value.Valid {
				_m.SubResource = value.String
			}
		case auditevent.FieldStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stage", values[i])
			} else if value.Valid {
				_m.Stage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AuditEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditEvent.
// Note that you need to call AuditEvent.Unwrap() before calling this method if this AuditEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditEvent) Update() *AuditEventUpdateOne {
	return NewAuditEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditEvent) Unwrap() *AuditEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AuditEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("raw=")
	builder.WriteString(_m.Raw)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(_m.Level)
	builder.WriteString(", ")
	builder.WriteString("auditID=")
	builder.WriteString(_m.AuditID)
	builder.WriteString(", ")
	builder.WriteString("verb=")
	builder.WriteString(_m.Verb)
	builder.WriteString(", ")
	builder.WriteString("userAgent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("requestTimestamp=")
	builder.WriteString(_m.RequestTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("stageTimestamp=")
	builder.WriteString(_m.StageTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("apiVersion=")
	builder.WriteString(_m.ApiVersion)
	builder.WriteString(", ")
	builder.WriteString("apiGroup=")
	builder.WriteString(_m.ApiGroup)
	builder.WriteString(", ")
	builder.WriteString("resource=")
	builder.WriteString(_m.Resource)
	builder.WriteString(", ")
	builder.WriteString("subResource=")
	builder.WriteString(_m.SubResource)
	builder.WriteString(", ")
	builder.WriteString("stage=")
	builder.WriteString(_m.Stage)
	builder.WriteByte(')')
	return builder.String()
}

// AuditEvents is a parsable slice of AuditEvent.
type AuditEvents []*AuditEvent
