// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/auditevent"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/view"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// AuditEventEdge is the edge representation of AuditEvent.
type AuditEventEdge struct {
	Node   *AuditEvent `json:"node"`
	Cursor Cursor      `json:"cursor"`
}

// AuditEventConnection is the connection containing edges to AuditEvent.
type AuditEventConnection struct {
	Edges      []*AuditEventEdge `json:"edges"`
	PageInfo   PageInfo          `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

func (c *AuditEventConnection) build(nodes []*AuditEvent, pager *auditeventPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *AuditEvent
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *AuditEvent {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *AuditEvent {
			return nodes[i]
		}
	}
	c.Edges = make([]*AuditEventEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &AuditEventEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// AuditEventPaginateOption enables pagination customization.
type AuditEventPaginateOption func(*auditeventPager) error

// WithAuditEventOrder configures pagination ordering.
func WithAuditEventOrder(order *AuditEventOrder) AuditEventPaginateOption {
	if order == nil {
		order = DefaultAuditEventOrder
	}
	o := *order
	return func(pager *auditeventPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultAuditEventOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithAuditEventFilter configures pagination filter.
func WithAuditEventFilter(filter func(*AuditEventQuery) (*AuditEventQuery, error)) AuditEventPaginateOption {
	return func(pager *auditeventPager) error {
		if filter == nil {
			return errors.New("AuditEventQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type auditeventPager struct {
	order  *AuditEventOrder
	filter func(*AuditEventQuery) (*AuditEventQuery, error)
}

func newAuditEventPager(opts []AuditEventPaginateOption) (*auditeventPager, error) {
	pager := &auditeventPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultAuditEventOrder
	}
	return pager, nil
}

func (p *auditeventPager) applyFilter(query *AuditEventQuery) (*AuditEventQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *auditeventPager) toCursor(ae *AuditEvent) Cursor {
	return p.order.Field.toCursor(ae)
}

func (p *auditeventPager) applyCursors(query *AuditEventQuery, after, before *Cursor) *AuditEventQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultAuditEventOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *auditeventPager) applyOrder(query *AuditEventQuery, reverse bool) *AuditEventQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultAuditEventOrder.Field {
		query = query.Order(direction.orderFunc(DefaultAuditEventOrder.Field.field))
	}
	return query
}

func (p *auditeventPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultAuditEventOrder.Field {
			b.Comma().Ident(DefaultAuditEventOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to AuditEvent.
func (ae *AuditEventQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...AuditEventPaginateOption,
) (*AuditEventConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newAuditEventPager(opts)
	if err != nil {
		return nil, err
	}
	if ae, err = pager.applyFilter(ae); err != nil {
		return nil, err
	}
	conn := &AuditEventConnection{Edges: []*AuditEventEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = ae.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	ae = pager.applyCursors(ae, after, before)
	ae = pager.applyOrder(ae, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		ae.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := ae.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := ae.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// AuditEventOrderField defines the ordering field of AuditEvent.
type AuditEventOrderField struct {
	field    string
	toCursor func(*AuditEvent) Cursor
}

// AuditEventOrder defines the ordering of AuditEvent.
type AuditEventOrder struct {
	Direction OrderDirection        `json:"direction"`
	Field     *AuditEventOrderField `json:"field"`
}

// DefaultAuditEventOrder is the default ordering of AuditEvent.
var DefaultAuditEventOrder = &AuditEventOrder{
	Direction: OrderDirectionAsc,
	Field: &AuditEventOrderField{
		field: auditevent.FieldID,
		toCursor: func(ae *AuditEvent) Cursor {
			return Cursor{ID: ae.ID}
		},
	},
}

// ToEdge converts AuditEvent into AuditEventEdge.
func (ae *AuditEvent) ToEdge(order *AuditEventOrder) *AuditEventEdge {
	if order == nil {
		order = DefaultAuditEventOrder
	}
	return &AuditEventEdge{
		Node:   ae,
		Cursor: order.Field.toCursor(ae),
	}
}

// ViewEdge is the edge representation of View.
type ViewEdge struct {
	Node   *View  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// ViewConnection is the connection containing edges to View.
type ViewConnection struct {
	Edges      []*ViewEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *ViewConnection) build(nodes []*View, pager *viewPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *View
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *View {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *View {
			return nodes[i]
		}
	}
	c.Edges = make([]*ViewEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ViewEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ViewPaginateOption enables pagination customization.
type ViewPaginateOption func(*viewPager) error

// WithViewOrder configures pagination ordering.
func WithViewOrder(order *ViewOrder) ViewPaginateOption {
	if order == nil {
		order = DefaultViewOrder
	}
	o := *order
	return func(pager *viewPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultViewOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithViewFilter configures pagination filter.
func WithViewFilter(filter func(*ViewQuery) (*ViewQuery, error)) ViewPaginateOption {
	return func(pager *viewPager) error {
		if filter == nil {
			return errors.New("ViewQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type viewPager struct {
	order  *ViewOrder
	filter func(*ViewQuery) (*ViewQuery, error)
}

func newViewPager(opts []ViewPaginateOption) (*viewPager, error) {
	pager := &viewPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultViewOrder
	}
	return pager, nil
}

func (p *viewPager) applyFilter(query *ViewQuery) (*ViewQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *viewPager) toCursor(v *View) Cursor {
	return p.order.Field.toCursor(v)
}

func (p *viewPager) applyCursors(query *ViewQuery, after, before *Cursor) *ViewQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultViewOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *viewPager) applyOrder(query *ViewQuery, reverse bool) *ViewQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultViewOrder.Field {
		query = query.Order(direction.orderFunc(DefaultViewOrder.Field.field))
	}
	return query
}

func (p *viewPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultViewOrder.Field {
			b.Comma().Ident(DefaultViewOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to View.
func (v *ViewQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ViewPaginateOption,
) (*ViewConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newViewPager(opts)
	if err != nil {
		return nil, err
	}
	if v, err = pager.applyFilter(v); err != nil {
		return nil, err
	}
	conn := &ViewConnection{Edges: []*ViewEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = v.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	v = pager.applyCursors(v, after, before)
	v = pager.applyOrder(v, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		v.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := v.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := v.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// ViewOrderField defines the ordering field of View.
type ViewOrderField struct {
	field    string
	toCursor func(*View) Cursor
}

// ViewOrder defines the ordering of View.
type ViewOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *ViewOrderField `json:"field"`
}

// DefaultViewOrder is the default ordering of View.
var DefaultViewOrder = &ViewOrder{
	Direction: OrderDirectionAsc,
	Field: &ViewOrderField{
		field: view.FieldID,
		toCursor: func(v *View) Cursor {
			return Cursor{ID: v.ID}
		},
	},
}

// ToEdge converts View into ViewEdge.
func (v *View) ToEdge(order *ViewOrder) *ViewEdge {
	if order == nil {
		order = DefaultViewOrder
	}
	return &ViewEdge{
		Node:   v,
		Cursor: order.Field.toCursor(v),
	}
}
