// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/predicate"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/resourcekind"
)

// ResourceKindUpdate is the builder for updating ResourceKind entities.
type ResourceKindUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceKindMutation
}

// Where appends a list predicates to the ResourceKindUpdate builder.
func (rku *ResourceKindUpdate) Where(ps ...predicate.ResourceKind) *ResourceKindUpdate {
	rku.mutation.Where(ps...)
	return rku
}

// SetName sets the "name" field.
func (rku *ResourceKindUpdate) SetName(s string) *ResourceKindUpdate {
	rku.mutation.SetName(s)
	return rku
}

// SetNillableName sets the "name" field if the given value is not nil.
func (rku *ResourceKindUpdate) SetNillableName(s *string) *ResourceKindUpdate {
	if s != nil {
		rku.SetName(*s)
	}
	return rku
}

// SetApiVersion sets the "apiVersion" field.
func (rku *ResourceKindUpdate) SetApiVersion(s string) *ResourceKindUpdate {
	rku.mutation.SetApiVersion(s)
	return rku
}

// SetNillableApiVersion sets the "apiVersion" field if the given value is not nil.
func (rku *ResourceKindUpdate) SetNillableApiVersion(s *string) *ResourceKindUpdate {
	if s != nil {
		rku.SetApiVersion(*s)
	}
	return rku
}

// SetNamespaced sets the "namespaced" field.
func (rku *ResourceKindUpdate) SetNamespaced(b bool) *ResourceKindUpdate {
	rku.mutation.SetNamespaced(b)
	return rku
}

// SetNillableNamespaced sets the "namespaced" field if the given value is not nil.
func (rku *ResourceKindUpdate) SetNillableNamespaced(b *bool) *ResourceKindUpdate {
	if b != nil {
		rku.SetNamespaced(*b)
	}
	return rku
}

// SetKind sets the "kind" field.
func (rku *ResourceKindUpdate) SetKind(s string) *ResourceKindUpdate {
	rku.mutation.SetKind(s)
	return rku
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (rku *ResourceKindUpdate) SetNillableKind(s *string) *ResourceKindUpdate {
	if s != nil {
		rku.SetKind(*s)
	}
	return rku
}

// Mutation returns the ResourceKindMutation object of the builder.
func (rku *ResourceKindUpdate) Mutation() *ResourceKindMutation {
	return rku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rku *ResourceKindUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rku.sqlSave, rku.mutation, rku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rku *ResourceKindUpdate) SaveX(ctx context.Context) int {
	affected, err := rku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rku *ResourceKindUpdate) Exec(ctx context.Context) error {
	_, err := rku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rku *ResourceKindUpdate) ExecX(ctx context.Context) {
	if err := rku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rku *ResourceKindUpdate) check() error {
	if v, ok := rku.mutation.Name(); ok {
		if err := resourcekind.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.name": %w`, err)}
		}
	}
	if v, ok := rku.mutation.ApiVersion(); ok {
		if err := resourcekind.ApiVersionValidator(v); err != nil {
			return &ValidationError{Name: "apiVersion", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.apiVersion": %w`, err)}
		}
	}
	if v, ok := rku.mutation.Kind(); ok {
		if err := resourcekind.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.kind": %w`, err)}
		}
	}
	return nil
}

func (rku *ResourceKindUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcekind.Table, resourcekind.Columns, sqlgraph.NewFieldSpec(resourcekind.FieldID, field.TypeInt))
	if ps := rku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rku.mutation.Name(); ok {
		_spec.SetField(resourcekind.FieldName, field.TypeString, value)
	}
	if value, ok := rku.mutation.ApiVersion(); ok {
		_spec.SetField(resourcekind.FieldApiVersion, field.TypeString, value)
	}
	if value, ok := rku.mutation.Namespaced(); ok {
		_spec.SetField(resourcekind.FieldNamespaced, field.TypeBool, value)
	}
	if value, ok := rku.mutation.Kind(); ok {
		_spec.SetField(resourcekind.FieldKind, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcekind.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rku.mutation.done = true
	return n, nil
}

// ResourceKindUpdateOne is the builder for updating a single ResourceKind entity.
type ResourceKindUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceKindMutation
}

// SetName sets the "name" field.
func (rkuo *ResourceKindUpdateOne) SetName(s string) *ResourceKindUpdateOne {
	rkuo.mutation.SetName(s)
	return rkuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (rkuo *ResourceKindUpdateOne) SetNillableName(s *string) *ResourceKindUpdateOne {
	if s != nil {
		rkuo.SetName(*s)
	}
	return rkuo
}

// SetApiVersion sets the "apiVersion" field.
func (rkuo *ResourceKindUpdateOne) SetApiVersion(s string) *ResourceKindUpdateOne {
	rkuo.mutation.SetApiVersion(s)
	return rkuo
}

// SetNillableApiVersion sets the "apiVersion" field if the given value is not nil.
func (rkuo *ResourceKindUpdateOne) SetNillableApiVersion(s *string) *ResourceKindUpdateOne {
	if s != nil {
		rkuo.SetApiVersion(*s)
	}
	return rkuo
}

// SetNamespaced sets the "namespaced" field.
func (rkuo *ResourceKindUpdateOne) SetNamespaced(b bool) *ResourceKindUpdateOne {
	rkuo.mutation.SetNamespaced(b)
	return rkuo
}

// SetNillableNamespaced sets the "namespaced" field if the given value is not nil.
func (rkuo *ResourceKindUpdateOne) SetNillableNamespaced(b *bool) *ResourceKindUpdateOne {
	if b != nil {
		rkuo.SetNamespaced(*b)
	}
	return rkuo
}

// SetKind sets the "kind" field.
func (rkuo *ResourceKindUpdateOne) SetKind(s string) *ResourceKindUpdateOne {
	rkuo.mutation.SetKind(s)
	return rkuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (rkuo *ResourceKindUpdateOne) SetNillableKind(s *string) *ResourceKindUpdateOne {
	if s != nil {
		rkuo.SetKind(*s)
	}
	return rkuo
}

// Mutation returns the ResourceKindMutation object of the builder.
func (rkuo *ResourceKindUpdateOne) Mutation() *ResourceKindMutation {
	return rkuo.mutation
}

// Where appends a list predicates to the ResourceKindUpdate builder.
func (rkuo *ResourceKindUpdateOne) Where(ps ...predicate.ResourceKind) *ResourceKindUpdateOne {
	rkuo.mutation.Where(ps...)
	return rkuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rkuo *ResourceKindUpdateOne) Select(field string, fields ...string) *ResourceKindUpdateOne {
	rkuo.fields = append([]string{field}, fields...)
	return rkuo
}

// Save executes the query and returns the updated ResourceKind entity.
func (rkuo *ResourceKindUpdateOne) Save(ctx context.Context) (*ResourceKind, error) {
	return withHooks(ctx, rkuo.sqlSave, rkuo.mutation, rkuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rkuo *ResourceKindUpdateOne) SaveX(ctx context.Context) *ResourceKind {
	node, err := rkuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rkuo *ResourceKindUpdateOne) Exec(ctx context.Context) error {
	_, err := rkuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rkuo *ResourceKindUpdateOne) ExecX(ctx context.Context) {
	if err := rkuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rkuo *ResourceKindUpdateOne) check() error {
	if v, ok := rkuo.mutation.Name(); ok {
		if err := resourcekind.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.name": %w`, err)}
		}
	}
	if v, ok := rkuo.mutation.ApiVersion(); ok {
		if err := resourcekind.ApiVersionValidator(v); err != nil {
			return &ValidationError{Name: "apiVersion", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.apiVersion": %w`, err)}
		}
	}
	if v, ok := rkuo.mutation.Kind(); ok {
		if err := resourcekind.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ResourceKind.kind": %w`, err)}
		}
	}
	return nil
}

func (rkuo *ResourceKindUpdateOne) sqlSave(ctx context.Context) (_node *ResourceKind, err error) {
	if err := rkuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourcekind.Table, resourcekind.Columns, sqlgraph.NewFieldSpec(resourcekind.FieldID, field.TypeInt))
	id, ok := rkuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceKind.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rkuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourcekind.FieldID)
		for _, f := range fields {
			if !resourcekind.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourcekind.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rkuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rkuo.mutation.Name(); ok {
		_spec.SetField(resourcekind.FieldName, field.TypeString, value)
	}
	if value, ok := rkuo.mutation.ApiVersion(); ok {
		_spec.SetField(resourcekind.FieldApiVersion, field.TypeString, value)
	}
	if value, ok := rkuo.mutation.Namespaced(); ok {
		_spec.SetField(resourcekind.FieldNamespaced, field.TypeBool, value)
	}
	if value, ok := rkuo.mutation.Kind(); ok {
		_spec.SetField(resourcekind.FieldKind, field.TypeString, value)
	}
	_node = &ResourceKind{config: rkuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rkuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcekind.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rkuo.mutation.done = true
	return _node, nil
}
