// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/strrl/kubernetes-auditing-dashboard/ent/auditevent"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescLevel is the schema descriptor for level field.
	auditeventDescLevel := auditeventFields[0].Descriptor()
	// auditevent.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	auditevent.LevelValidator = auditeventDescLevel.Validators[0].(func(string) error)
	// auditeventDescAuditID is the schema descriptor for auditID field.
	auditeventDescAuditID := auditeventFields[1].Descriptor()
	// auditevent.AuditIDValidator is a validator for the "auditID" field. It is called by the builders before save.
	auditevent.AuditIDValidator = auditeventDescAuditID.Validators[0].(func(string) error)
	// auditeventDescVerb is the schema descriptor for verb field.
	auditeventDescVerb := auditeventFields[2].Descriptor()
	// auditevent.VerbValidator is a validator for the "verb" field. It is called by the builders before save.
	auditevent.VerbValidator = auditeventDescVerb.Validators[0].(func(string) error)
	// auditeventDescUserAgent is the schema descriptor for userAgent field.
	auditeventDescUserAgent := auditeventFields[3].Descriptor()
	// auditevent.UserAgentValidator is a validator for the "userAgent" field. It is called by the builders before save.
	auditevent.UserAgentValidator = auditeventDescUserAgent.Validators[0].(func(string) error)
	// auditeventDescRaw is the schema descriptor for raw field.
	auditeventDescRaw := auditeventFields[4].Descriptor()
	// auditevent.RawValidator is a validator for the "raw" field. It is called by the builders before save.
	auditevent.RawValidator = auditeventDescRaw.Validators[0].(func(string) error)
}
