// Code generated by ent, DO NOT EDIT.

package auditevent

const (
	// Label holds the string label denoting the auditevent type in the database.
	Label = "audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldAuditID holds the string denoting the auditid field in the database.
	FieldAuditID = "audit_id"
	// FieldVerb holds the string denoting the verb field in the database.
	FieldVerb = "verb"
	// FieldUserAgent holds the string denoting the useragent field in the database.
	FieldUserAgent = "user_agent"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldRequestTimestamp holds the string denoting the requesttimestamp field in the database.
	FieldRequestTimestamp = "request_timestamp"
	// FieldStageTimestamp holds the string denoting the stagetimestamp field in the database.
	FieldStageTimestamp = "stage_timestamp"
	// Table holds the table name of the auditevent in the database.
	Table = "audit_events"
)

// Columns holds all SQL columns for auditevent fields.
var Columns = []string{
	FieldID,
	FieldLevel,
	FieldAuditID,
	FieldVerb,
	FieldUserAgent,
	FieldRaw,
	FieldRequestTimestamp,
	FieldStageTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(string) error
	// AuditIDValidator is a validator for the "auditID" field. It is called by the builders before save.
	AuditIDValidator func(string) error
	// VerbValidator is a validator for the "verb" field. It is called by the builders before save.
	VerbValidator func(string) error
	// UserAgentValidator is a validator for the "userAgent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// RawValidator is a validator for the "raw" field. It is called by the builders before save.
	RawValidator func(string) error
)
