// Code generated by ent, DO NOT EDIT.

package resourcekind

import (
	"entgo.io/ent/dialect/sql"
	"github.com/strrl/kubernetes-auditing-dashboard/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldName, v))
}

// ApiVersion applies equality check predicate on the "apiVersion" field. It's identical to ApiVersionEQ.
func ApiVersion(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldApiVersion, v))
}

// Namespaced applies equality check predicate on the "namespaced" field. It's identical to NamespacedEQ.
func Namespaced(v bool) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldNamespaced, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldKind, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContainsFold(FieldName, v))
}

// ApiVersionEQ applies the EQ predicate on the "apiVersion" field.
func ApiVersionEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldApiVersion, v))
}

// ApiVersionNEQ applies the NEQ predicate on the "apiVersion" field.
func ApiVersionNEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNEQ(FieldApiVersion, v))
}

// ApiVersionIn applies the In predicate on the "apiVersion" field.
func ApiVersionIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldIn(FieldApiVersion, vs...))
}

// ApiVersionNotIn applies the NotIn predicate on the "apiVersion" field.
func ApiVersionNotIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNotIn(FieldApiVersion, vs...))
}

// ApiVersionGT applies the GT predicate on the "apiVersion" field.
func ApiVersionGT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGT(FieldApiVersion, v))
}

// ApiVersionGTE applies the GTE predicate on the "apiVersion" field.
func ApiVersionGTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGTE(FieldApiVersion, v))
}

// ApiVersionLT applies the LT predicate on the "apiVersion" field.
func ApiVersionLT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLT(FieldApiVersion, v))
}

// ApiVersionLTE applies the LTE predicate on the "apiVersion" field.
func ApiVersionLTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLTE(FieldApiVersion, v))
}

// ApiVersionContains applies the Contains predicate on the "apiVersion" field.
func ApiVersionContains(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContains(FieldApiVersion, v))
}

// ApiVersionHasPrefix applies the HasPrefix predicate on the "apiVersion" field.
func ApiVersionHasPrefix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasPrefix(FieldApiVersion, v))
}

// ApiVersionHasSuffix applies the HasSuffix predicate on the "apiVersion" field.
func ApiVersionHasSuffix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasSuffix(FieldApiVersion, v))
}

// ApiVersionEqualFold applies the EqualFold predicate on the "apiVersion" field.
func ApiVersionEqualFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEqualFold(FieldApiVersion, v))
}

// ApiVersionContainsFold applies the ContainsFold predicate on the "apiVersion" field.
func ApiVersionContainsFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContainsFold(FieldApiVersion, v))
}

// NamespacedEQ applies the EQ predicate on the "namespaced" field.
func NamespacedEQ(v bool) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldNamespaced, v))
}

// NamespacedNEQ applies the NEQ predicate on the "namespaced" field.
func NamespacedNEQ(v bool) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNEQ(FieldNamespaced, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.ResourceKind {
	return predicate.ResourceKind(sql.FieldContainsFold(FieldKind, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourceKind) predicate.ResourceKind {
	return predicate.ResourceKind(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourceKind) predicate.ResourceKind {
	return predicate.ResourceKind(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourceKind) predicate.ResourceKind {
	return predicate.ResourceKind(func(s *sql.Selector) {
		p(s.Not())
	})
}
