apiVersion: audit.k8s.io/v1
kind: Policy
omitStages: []
rules:
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["*"]
  - level: Metadata
    nonResourceURLs:
    - "/api*"
    - "/version"
