// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)
